#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 17 20:55:11 2019

@author: nephilim
"""
from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_NewModel(QtWidgets.QDialog):
    def __init__(self,parent=None):
        super(Ui_NewModel,self).__init__(parent)
        self.setObjectName("Dialog")
        self.setWindowTitle('Create New Model')
        self.setFixedSize(600, 400)
        self.frame = QtWidgets.QFrame(self)
        self.frame.setGeometry(QtCore.QRect(10, 10, 580, 380))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 550, 170))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_GraphicParameter = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_GraphicParameter.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_GraphicParameter.setObjectName("gridLayout_GraphicParameter")
        # Graphic Parameter Label
        self.label_GraphicParameter = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_GraphicParameter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GraphicParameter.setObjectName("label_GraphicParameter")
        self.label_GraphicParameter.setText('Graphic Parameter')
        self.gridLayout_GraphicParameter.addWidget(self.label_GraphicParameter, 0, 0, 1, 1)
        # X Range Label
        self.label_xRange = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_xRange.setAlignment(QtCore.Qt.AlignCenter)
        self.label_xRange.setObjectName("label_xRange")
        self.label_xRange.setText('X Range')
        self.gridLayout_GraphicParameter.addWidget(self.label_xRange, 1, 0, 1, 1)
        # Z Range Label
        self.label_zRange = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_zRange.setAlignment(QtCore.Qt.AlignCenter)
        self.label_zRange.setObjectName("label_zRange")
        self.label_zRange.setText('Z Range')
        self.gridLayout_GraphicParameter.addWidget(self.label_zRange, 2, 0, 1, 1)
        # dx Label
        self.label_dx = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_dx.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dx.setObjectName("label_dx")
        self.label_dx.setText('dx')
        self.gridLayout_GraphicParameter.addWidget(self.label_dx, 3, 0, 1, 1)
        # dz Label
        self.label_dz = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_dz.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dz.setObjectName("label_dz")
        self.label_dz.setText('dz')
        self.gridLayout_GraphicParameter.addWidget(self.label_dz, 4, 0, 1, 1)
        # dt Label
        self.label_dt = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_dt.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dt.setObjectName("label_dt")
        self.label_dt.setText('dt')
        self.gridLayout_GraphicParameter.addWidget(self.label_dt, 5, 0, 1, 1)
        # Simulation Time Label
        self.label_SimulationTime = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_SimulationTime.setAlignment(QtCore.Qt.AlignCenter)
        self.label_SimulationTime.setObjectName("label_SimulationTime")
        self.label_SimulationTime.setText('Simulation Time')
        self.gridLayout_GraphicParameter.addWidget(self.label_SimulationTime, 1, 2, 1, 1)
        # Source Star Label
        self.label_SourceStart = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_SourceStart.setAlignment(QtCore.Qt.AlignCenter)
        self.label_SourceStart.setObjectName("label_SourceStart")
        self.label_SourceStart.setText('Source Start')
        self.gridLayout_GraphicParameter.addWidget(self.label_SourceStart, 2, 2, 1, 1)
        # Receiver Label
        self.label_Receiver = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_Receiver.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Receiver.setObjectName("label_Receiver")
        self.label_Receiver.setText('Receiver Start')
        self.gridLayout_GraphicParameter.addWidget(self.label_Receiver, 3, 2, 1, 1)
        # Step Label
        self.label_Step = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_Step.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Step.setObjectName("label_Step")
        self.label_Step.setText('Step')
        self.gridLayout_GraphicParameter.addWidget(self.label_Step, 4, 2, 1, 1)
        # Scan Label
        self.label_Scan = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_Scan.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Scan.setObjectName("label_Scan")
        self.label_Scan.setText('Scan')
        self.gridLayout_GraphicParameter.addWidget(self.label_Scan, 5, 2, 1, 1)
        # X Range doubleSpinBox
        self.doubleSpinBox_xRange = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_xRange.setMinimum(0.0)
        self.doubleSpinBox_xRange.setMaximum(100.0)
        self.doubleSpinBox_xRange.setSingleStep(0.5)
        self.doubleSpinBox_xRange.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_xRange.setProperty("value", 1.0)
        self.doubleSpinBox_xRange.setObjectName("doubleSpinBox_xRange") 
        self.gridLayout_GraphicParameter.addWidget(self.doubleSpinBox_xRange, 1, 1, 1, 1)
        # Z Range doubleSpinBox
        self.doubleSpinBox_zRange = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_zRange.setMinimum(0.0)
        self.doubleSpinBox_zRange.setMaximum(100.0)
        self.doubleSpinBox_zRange.setSingleStep(0.5)
        self.doubleSpinBox_zRange.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_zRange.setProperty("value", 1.0)
        self.doubleSpinBox_zRange.setObjectName("doubleSpinBox_zRange") 
        self.gridLayout_GraphicParameter.addWidget(self.doubleSpinBox_zRange, 2, 1, 1, 1)
        # dx Range LineEdit
        self.lineEdit_dx = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_dx.sizePolicy().hasHeightForWidth())
        self.lineEdit_dx.setSizePolicy(sizePolicy)
        self.lineEdit_dx.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit_dx.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_dx.setObjectName("lineEdit_dx")
        self.lineEdit_dx.setPlaceholderText('0.0025')
        pDoubleValidator=QtGui.QDoubleValidator(self)
        pDoubleValidator.setRange(0,1.0)
        pDoubleValidator.setDecimals(10)
        self.lineEdit_dx.setValidator(pDoubleValidator)
        self.gridLayout_GraphicParameter.addWidget(self.lineEdit_dx, 3, 1, 1, 1)
        # dz Range LineEdit
        self.lineEdit_dz = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_dz.sizePolicy().hasHeightForWidth())
        self.lineEdit_dz.setSizePolicy(sizePolicy)
        self.lineEdit_dz.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit_dz.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_dz.setObjectName("lineEdit_dz")
        self.lineEdit_dz.setPlaceholderText('0.0025')
        pDoubleValidator=QtGui.QDoubleValidator(self)
        pDoubleValidator.setRange(0,1.0)
        pDoubleValidator.setDecimals(10)
        self.lineEdit_dz.setValidator(pDoubleValidator)
        self.gridLayout_GraphicParameter.addWidget(self.lineEdit_dz, 4, 1, 1, 1)
        # dt Range LineEdit
        self.lineEdit_dt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_dt.sizePolicy().hasHeightForWidth())
        self.lineEdit_dt.setSizePolicy(sizePolicy)
        self.lineEdit_dt.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit_dt.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_dt.setObjectName("lineEdit_dt")
        self.lineEdit_dt.setPlaceholderText('1e-11')
        pDoubleRegex = QtCore.QRegExp("[+-]?[\\d]+([\\.][\\d]*)?([Ee][+-]?[0-9]{0,6})?")
        pDoubleValidator = QtGui.QRegExpValidator(pDoubleRegex, self.lineEdit_dt)
        self.lineEdit_dt.setValidator(pDoubleValidator)
        self.gridLayout_GraphicParameter.addWidget(self.lineEdit_dt, 5, 1, 1, 1)
        # Simulation Time LineEdit
        self.lineEdit_SimulationTime = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_SimulationTime.sizePolicy().hasHeightForWidth())
        self.lineEdit_SimulationTime.setSizePolicy(sizePolicy)
        self.lineEdit_SimulationTime.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit_SimulationTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_SimulationTime.setObjectName("lineEdit_dx")
        self.lineEdit_SimulationTime.setPlaceholderText('7e-8')
        pDoubleRegex = QtCore.QRegExp("[+-]?[\\d]+([\\.][\\d]*)?([Ee][+-]?[0-9]{0,6})?")
        pDoubleValidator = QtGui.QRegExpValidator(pDoubleRegex, self.lineEdit_SimulationTime)
        self.lineEdit_SimulationTime.setValidator(pDoubleValidator)
        self.gridLayout_GraphicParameter.addWidget(self.lineEdit_SimulationTime, 1, 3, 1, 1)
        # Source Start LineEdit
        self.lineEdit_SourceStart = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_SourceStart.sizePolicy().hasHeightForWidth())
        self.lineEdit_SourceStart.setSizePolicy(sizePolicy)
        self.lineEdit_SourceStart.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit_SourceStart.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_SourceStart.setObjectName("lineEdit_SourceStart")
        self.lineEdit_SourceStart.setPlaceholderText('0,0')
        # pDoubleValidator=QtGui.QDoubleValidator(self)
        # pDoubleValidator.setRange(0,100.0)
        # pDoubleValidator.setDecimals(10)
        # self.lineEdit_SourceStart.setValidator(pDoubleValidator)
        self.gridLayout_GraphicParameter.addWidget(self.lineEdit_SourceStart, 2, 3, 1, 1)
        # Receiver Start LineEdit
        self.lineEdit_ReceiverStart = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ReceiverStart.sizePolicy().hasHeightForWidth())
        self.lineEdit_ReceiverStart.setSizePolicy(sizePolicy)
        self.lineEdit_ReceiverStart.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit_ReceiverStart.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ReceiverStart.setObjectName("lineEdit_ReceiverStart")
        self.lineEdit_ReceiverStart.setPlaceholderText('0,0')
        # pDoubleValidator=QtGui.QDoubleValidator(self)
        # pDoubleValidator.setRange(0,100.0)
        # pDoubleValidator.setDecimals(10)
        # self.lineEdit_ReceiverStart.setValidator(pDoubleValidator)
        self.gridLayout_GraphicParameter.addWidget(self.lineEdit_ReceiverStart, 3, 3, 1, 1)
        # Step LineEdit
        self.lineEdit_Step = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Step.sizePolicy().hasHeightForWidth())
        self.lineEdit_Step.setSizePolicy(sizePolicy)
        self.lineEdit_Step.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit_Step.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Step.setObjectName("lineEdit_Step")
        self.lineEdit_Step.setPlaceholderText('0.0025')
        pDoubleValidator=QtGui.QDoubleValidator(self)
        pDoubleValidator.setRange(0,10.0)
        pDoubleValidator.setDecimals(10)
        self.lineEdit_Step.setValidator(pDoubleValidator)
        self.gridLayout_GraphicParameter.addWidget(self.lineEdit_Step, 4, 3, 1, 1)
        # Scan LineEdit
        self.lineEdit_Scan = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Scan.sizePolicy().hasHeightForWidth())
        self.lineEdit_Scan.setSizePolicy(sizePolicy)
        self.lineEdit_Scan.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit_Scan.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Scan.setObjectName("lineEdit_Scan")
        self.lineEdit_Scan.setPlaceholderText('400')
        pDoubleValidator=QtGui.QDoubleValidator(self)
        pDoubleValidator.setRange(1,10000)
        pDoubleValidator.setDecimals(0)
        self.lineEdit_Scan.setValidator(pDoubleValidator)
        self.gridLayout_GraphicParameter.addWidget(self.lineEdit_Scan, 5, 3, 1, 1)
        # Set Graphic Parameter GridLayout
        self.gridLayout_GraphicParameter.setColumnStretch(0, 10)
        self.gridLayout_GraphicParameter.setColumnStretch(1, 20)
        self.gridLayout_GraphicParameter.setColumnStretch(2, 10)
        self.gridLayout_GraphicParameter.setColumnStretch(3, 20)
        self.gridLayout_GraphicParameter.setRowStretch(0, 1)
        self.gridLayout_GraphicParameter.setRowStretch(1, 1)
        self.gridLayout_GraphicParameter.setRowStretch(2, 1)
        self.gridLayout_GraphicParameter.setRowStretch(3, 1)
        self.gridLayout_GraphicParameter.setRowStretch(4, 1)
        # 
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 200, 550, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_BackgroundParameter = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_BackgroundParameter.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_BackgroundParameter.setObjectName("gridLayout_BackgroundParameter")
        
        # Background Parameter Label
        self.label_BackgroundParameter = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_BackgroundParameter.setObjectName("label_BackgroundParameter")
        self.label_BackgroundParameter.setText('Background parameter')
        self.gridLayout_BackgroundParameter.addWidget(self.label_BackgroundParameter, 0, 0, 1, 1)
        # Conductivity Label
        self.label_Conductivity = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_Conductivity.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Conductivity.setObjectName("label_Conductivity")
        self.label_Conductivity.setText('Conductivity')
        self.gridLayout_BackgroundParameter.addWidget(self.label_Conductivity, 1, 0, 1, 1)
        # Dielectric Constant Label
        self.label_DielectricConstant = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_DielectricConstant.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DielectricConstant.setObjectName("label_DielectricConstant")
        self.label_DielectricConstant.setText('Dielectric constant')
        self.gridLayout_BackgroundParameter.addWidget(self.label_DielectricConstant, 2, 0, 1, 1)
        # Magnetic Permeability Label
        self.label_MagneticPermeability = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_MagneticPermeability.setAlignment(QtCore.Qt.AlignCenter)
        self.label_MagneticPermeability.setObjectName("label_MagneticPermeability")
        self.label_MagneticPermeability.setText('Magnetic permeability')
        self.gridLayout_BackgroundParameter.addWidget(self.label_MagneticPermeability, 1, 2, 1, 1)
        # Frequency Label
        self.label_Frequency = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_Frequency.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Frequency.setObjectName("label_Frequency")
        self.label_Frequency.setText('Frequency')
        self.gridLayout_BackgroundParameter.addWidget(self.label_Frequency, 2, 2, 1, 1)
        # Conductivity lineEdit
        self.lineEdit_Conductivity = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Conductivity.sizePolicy().hasHeightForWidth())
        self.lineEdit_Conductivity.setSizePolicy(sizePolicy)
        self.lineEdit_Conductivity.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit_Conductivity.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Conductivity.setObjectName("lineEdit_Conductivity")
        self.lineEdit_Conductivity.setPlaceholderText('1e-5')
        pDoubleRegex = QtCore.QRegExp("[+-]?[\\d]+([\\.][\\d]*)?([Ee][+-]?[0-9]{0,6})?")
        pDoubleValidator = QtGui.QRegExpValidator(pDoubleRegex, self.lineEdit_Conductivity)
        self.lineEdit_Conductivity.setValidator(pDoubleValidator)
        self.gridLayout_BackgroundParameter.addWidget(self.lineEdit_Conductivity, 1, 1, 1, 1)
        # Dielectric Constant doubleSpinBox        
        self.doubleSpinBox_DielectricConstant = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_DielectricConstant.setMinimum(0.0)
        self.doubleSpinBox_DielectricConstant.setMaximum(81.0)
        self.doubleSpinBox_DielectricConstant.setSingleStep(0.5)
        self.doubleSpinBox_DielectricConstant.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_DielectricConstant.setProperty("value", 7.0)
        self.doubleSpinBox_DielectricConstant.setObjectName("doubleSpinBox_DielectricConstant") 
        self.gridLayout_BackgroundParameter.addWidget(self.doubleSpinBox_DielectricConstant, 2, 1, 1, 1)
        # Magnetic Permeability lineEdit
        self.lineEdit_MagneticPermeability = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_MagneticPermeability.sizePolicy().hasHeightForWidth())
        self.lineEdit_MagneticPermeability.setSizePolicy(sizePolicy)
        self.lineEdit_MagneticPermeability.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit_MagneticPermeability.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_MagneticPermeability.setObjectName("lineEdit_MagneticPermeability")
        self.lineEdit_MagneticPermeability.setPlaceholderText('1')
        pDoubleRegex = QtCore.QRegExp("[+-]?[\\d]+([\\.][\\d]*)?([Ee][+-]?[0-9]{0,6})?")
        pDoubleValidator = QtGui.QRegExpValidator(pDoubleRegex, self.lineEdit_MagneticPermeability)
        self.lineEdit_MagneticPermeability.setValidator(pDoubleValidator)
        self.gridLayout_BackgroundParameter.addWidget(self.lineEdit_MagneticPermeability, 1, 3, 1, 1)
        # Frequency doubleSpinBox
        self.lineEdit_Frequency = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Frequency.sizePolicy().hasHeightForWidth())
        self.lineEdit_Frequency.setSizePolicy(sizePolicy)
        self.lineEdit_Frequency.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit_Frequency.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Frequency.setObjectName("lineEdit_Frequency")
        self.lineEdit_Frequency.setPlaceholderText('4e8')
        pDoubleRegex = QtCore.QRegExp("[+-]?[\\d]+([\\.][\\d]*)?([Ee][+-]?[0-9]{0,6})?")
        pDoubleValidator = QtGui.QRegExpValidator(pDoubleRegex, self.lineEdit_Frequency)
        self.lineEdit_Frequency.setValidator(pDoubleValidator)
        self.gridLayout_BackgroundParameter.addWidget(self.lineEdit_Frequency, 2, 3, 1, 1)
        # Set Background Parameter GridLayout
        self.gridLayout_BackgroundParameter.setColumnStretch(0, 10)
        self.gridLayout_BackgroundParameter.setColumnStretch(1, 20)
        self.gridLayout_BackgroundParameter.setColumnStretch(2, 10)
        self.gridLayout_BackgroundParameter.setColumnStretch(3, 20)
        self.gridLayout_BackgroundParameter.setRowStretch(0, 1)
        self.gridLayout_BackgroundParameter.setRowStretch(1, 1)
        self.gridLayout_BackgroundParameter.setRowStretch(2, 1)
        # Buttion Ok
        self.pushButtonOk = QtWidgets.QPushButton(self.frame)
        self.pushButtonOk.setGeometry(QtCore.QRect(150, 340, 90, 30))
        self.pushButtonOk.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonOk.setObjectName("pushButtonOk")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./UI_Ico/ok.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonOk.setIcon(icon)
        self.pushButtonOk.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonOk.setText('Ok')
        # Buttion Cancel
        self.pushButtonCancel = QtWidgets.QPushButton(self.frame)
        self.pushButtonCancel.setGeometry(QtCore.QRect(350, 340, 90, 30))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./UI_Ico/cancel.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCancel.setIcon(icon)
        self.pushButtonCancel.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonCancel.setText('Cancel')
        
        self.pushButtonOk.clicked.connect(self.accept)
        self.pushButtonCancel.clicked.connect(self.reject)
        
        # if self.exec_() == self.Accepted:
        #     print('Accept')
        # else:
        #     print('Reject')
        
if __name__=='__main__':
    import sys
    try:
        app
    except:                
        app=QtWidgets.QApplication(sys.argv)
    ex = Ui_NewModel()
    ex.show()
    sys.exit(app.exec_())
